CREATE TRIGGER rate_update
AFTER INSERT OR UPDATE ON ratings
FOR EACH ROW EXECUTE PROCEDURE invalid();

CREATE OR REPLACE FUNCTION invalid() RETURNS trigger AS
$$
	BEGIN
		IF NEW.rate_value <= 0 THEN 
 			RAISE EXCEPTION  'RATE MUST BE HIGHER THAN 0';
		END IF;
		RETURN NULL;
	END;
$$ 
LANGUAGE 'plpgsql';

